[package]
name = "gitnuro-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
name = "gitnuro_rs"

[dependencies]
uniffi = { version = "0.24.1" }
notify = "6.0.1"
thiserror = "1.0.43"
libssh-rs = "0.2.1"

[build-dependencies]
uniffi = { version = "0.24.1", features = [ "build" ] }

[[bin]]
# This can be whatever name makes sense for your project, but the rest of this tutorial assumes uniffi-bindgen.
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
